#cd to /mnt
[[mgr.prepend_keymap]]
on   = [ "g", "m" ]
run  = "cd /mnt"
desc = "Cd to /mnt"

#cd to trash
[[mgr.prepend_keymap]]
on   = [ "g", "t" ]
run  = "cd $HOME/.local/share/Trash"
desc = "Cd to ~/.local/share/Trash"

# Root directory
[[mgr.prepend_keymap]]
on   = [ "g", "r" ]
run  = "cd /"
desc = "Cd to root"

#media usb
[[mgr.prepend_keymap]]
on   = [ "g", "u" ]
run  = "cd /run/media/histed"
desc = "Cd to Removable drive/usb drive"

# cd to .local
[[mgr.prepend_keymap]]
on   = [ "g", "l" ]
run  = "cd $HOME/.local"
desc = "Cd to ~/.local"

